# -*- makefile -*-
# Includes for hub applications.  Can manipulate these so that
# applications are built with a consistent set of compiler flags.
#
# Also controls cross compiling.
#
# @author Stephen Dawson-Haggerty <sdh@peoplepowerco.com>

# global settings

# Yvan: for some reason, SIGIO signals are not generated with the -O2 or -Os option
CFLAGS = -Os

LIBXML2_VERSION=libxml2-2.7.8
LIBCURL_VERSION=curl-7.21.7
OPENSSL_VERSION=openssl-1.0.0d
CJSON_VERSION=cJSON

