/*
 *  Copyright 2013 People Power Company
 *  
 *  This code was developed with funding from People Power Company
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * This module is responsible for activating the proxy with the server,
 * which will link the physical instance of this proxy to a group or username.
 * There are multiple ways to do this, and this activation functionality
 * here is only one of those multiple ways.
 *
 * @author David Moss
 */


#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <stdlib.h>
#include <stdbool.h>
#include <rpc/types.h>
#include <stdio.h>

#include <libxml/parser.h>

#include "libhttpcomm.h"
#include "libconfigio.h"
#include "eui64.h"
#include "proxyserver.h"
#include "proxyactivation.h"
#include "proxycli.h"
#include "ioterror.h"
#include "iotdebug.h"
#include "proxycli.h"
#include "proxy.h"


/***************** Private Prototypes ****************/
static void _proxyactivation_xml_startElementHandler(void *ctx, const xmlChar *name, const xmlChar **atts);

static void _proxyactivation_xml_charactersHandler(void *ctx, const xmlChar *ch, int len);


/***************** Public Functions ***************/
/**
 * Activate this proxy
 *
 * To activate, we need 4 things:
 *   1. The activation key, generated by the server which maps to the user's login
 *   2. The MAC address of this proxy
 *   3. The device type of this proxy, usually type 3
 *   4. The activation URL to send the request to
 *
 * We pass in the activation key from the command line
 * We obtain the MAC address through the EUI64 module.
 * We obtain the device type and activation URL from the configuration file
 *
 * @param activationKey the key to activate with
 * @param optionalUsername the username we activated with, or NULL
 * @return SUCCESS if the proxy was activated, FAIL if it wasn't
 */
error_t proxyactivation_activate(const char *activationKey, const char *optionalUsername) {
  char eui64[EUI64_STRING_SIZE];
  char url[PATH_MAX];
  char baseUrl[PATH_MAX];
  char deviceType[8];
  char rxBuffer[PROXY_MAX_MSG_LEN];
  char oBuffer[PROXY_MAX_MSG_LEN];
  http_param_t params;
  activation_info_t activationInfo;

  xmlSAXHandler saxHandler = {
      NULL, // internalSubsetHandler,
      NULL, // isStandaloneHandler,
      NULL, // hasInternalSubsetHandler,
      NULL, // hasExternalSubsetHandler,
      NULL, // resolveEntityHandler,
      NULL, // getEntityHandler,
      NULL, // entityDeclHandler,
      NULL, // notationDeclHandler,
      NULL, // attributeDeclHandler,
      NULL, // elementDeclHandler,
      NULL, // unparsedEntityDeclHandler,
      NULL, // setDocumentLocatorHandler,
      NULL, // startDocument
      NULL, // endDocument
      _proxyactivation_xml_startElementHandler, // startElement
      NULL, // endElement
      NULL, // reference,
      _proxyactivation_xml_charactersHandler, //characters
      NULL, // ignorableWhitespace
      NULL, // processingInstructionHandler,
      NULL, // comment
      NULL, // warning
      NULL, // error
      NULL, // fatal
  };

  bzero(deviceType, sizeof(deviceType));

  // Get the EUI64 unique device id for the proxy
  if(eui64_toString(eui64, sizeof(eui64)) != SUCCESS) {
    return FAIL;
  }

  // Read the activation URL from the configuration file
  if(libconfigio_read(proxycli_getConfigFilename(), CONFIGIO_ACTIVATION_URL_TOKEN_NAME, baseUrl, sizeof(baseUrl)) == -1) {
    printf("Couldn't read %s in file %s, writing default value\n", CONFIGIO_ACTIVATION_URL_TOKEN_NAME, proxycli_getConfigFilename());
    libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_ACTIVATION_URL_TOKEN_NAME, DEFAULT_ACTIVATION_URL);
    strncpy(baseUrl, DEFAULT_ACTIVATION_URL, sizeof(baseUrl));
  }

  // Read the device type from the configuration file
  if(libconfigio_read(proxycli_getConfigFilename(), CONFIGIO_PROXY_DEVICE_TYPE_TOKEN_NAME, deviceType, sizeof(deviceType)) == -1) {
    printf("Couldn't read %s in file %s, writing default value\n", CONFIGIO_PROXY_DEVICE_TYPE_TOKEN_NAME, proxycli_getConfigFilename());
    libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_PROXY_DEVICE_TYPE_TOKEN_NAME, DEFAULT_PROXY_DEVICETYPE);
    strncpy(deviceType, DEFAULT_PROXY_DEVICETYPE, sizeof(deviceType));
  }

  snprintf(url, sizeof(url), "%s/hubActivation", baseUrl);

  SYSLOG_INFO("Activation...");
  SYSLOG_INFO("Contacting URL %s\n", url);

  snprintf(oBuffer, sizeof(oBuffer), "<request>\n"
    "<hubActivation>\n"
    "<activationKey>%s</activationKey>\n"
    "<hubId>%s</hubId>\n"
    "<deviceType>%s</deviceType>\n"
    "</hubActivation>\n"
    "</request>\n", activationKey, eui64, deviceType);

  params.verbose = TRUE;
  params.timeouts.connectTimeout = HTTPCOMM_DEFAULT_CONNECT_TIMEOUT_SEC;
  params.timeouts.transferTimeout = HTTPCOMM_DEFAULT_TRANSFER_TIMEOUT_SEC;

  libhttpcomm_sendMsg(NULL, CURLOPT_POST, url, NULL, NULL, oBuffer, strlen(oBuffer), rxBuffer, sizeof(rxBuffer), params, NULL);

  SYSLOG_INFO("Server returned: \n%s\n", rxBuffer);

  if(0 != xmlSAXUserParseMemory(&saxHandler, &activationInfo, rxBuffer, strlen(rxBuffer))) {
    return FAIL;
  }

  if(activationInfo.resultCode == 0) {
    if(optionalUsername != NULL) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_PROXY_ACTIVATION_USERNAME, optionalUsername);
    }
    return SUCCESS;

  } else {
    return FAIL;
  }
}


/***************** Private Functions ****************/
/**
 * Parse a new XML tag
 */
static void _proxyactivation_xml_startElementHandler(void *ctx, const xmlChar *name, const xmlChar **atts) {
    // Know which tag we're grabbing character data out of
    snprintf(((activation_info_t *) ctx)->xmlTag, ACTIVATION_XML_TAG_SIZE, "%s", (char *) name);
}

/**
 * Parse the characters found as the value of an XML tag
 */
static void _proxyactivation_xml_charactersHandler(void *ctx, const xmlChar *ch, int len) {
  int i;
  char output[ACTIVATION_XML_VALUE_SIZE];
  activation_info_t *activationInfo = (activation_info_t *) ctx;

  if (len > 0 && len < ACTIVATION_XML_VALUE_SIZE) {
    for (i = 0; i < len; i++) {
      //if not equal a LF, CR store the character
      if ((ch[i] != 10) && (ch[i] != 13)) {
        output[i] = ch[i];
      }
    }
    output[i] = '\0';

    if (strcmp(activationInfo->xmlTag, "response") == 0) {
      // Tag is ok, but do nothing

    } else if (strcmp(activationInfo->xmlTag, "hubActivation") == 0) {
      // Tag is ok, but do nothing

    } else if (strcmp(activationInfo->xmlTag, "resultCode") == 0) {
      activationInfo->resultCode = atoi(output);

    } else if (strcmp(activationInfo->xmlTag, "host") == 0) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_CLOUD_HOST, output);

    } else if (strcmp(activationInfo->xmlTag, "port") == 0) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_CLOUD_PORT, output);

    } else if (strcmp(activationInfo->xmlTag, "uri") == 0) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_CLOUD_URI, output);

    } else if (strcmp(activationInfo->xmlTag, "useSSL") == 0) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_CLOUD_USE_SSL, output);

    } else if (strcmp(activationInfo->xmlTag, "deviceAuthToken") == 0) {
      libconfigio_write(proxycli_getConfigFilename(), CONFIGIO_CLOUD_ACTIVATION_KEY, output);

    } else {
      SYSLOG_DEBUG("Activation does not support XML tag %s", activationInfo->xmlTag);
    }

  } else {
    SYSLOG_ERR("Received an XML value that is too long to parse");
  }
}




